version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/db?schema=public"
      SERVER_PORT: 3000
      SERVER_ADDRESS: "0.0.0.0"
    ports:
      - "5000:3000"

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db